### PR TITLE
Update gitian-win-darkcoin.yml

### PR DESCRIPTION
**Pull request by schinzelh**
Trying to add Darkcoil to Bamboo

### CODE REVIEW

**Comment by vertoe** [comment]
Thanks.

**Comment by vertoe** [comment]
Keep an eye on the branding: "darkcoil" ;-)

**Comment by schinzelh** [comment]
Fixed :)

Can you additionally tag this revision?

**Comment by vertoe** [comment]
https://github.com/vertoe/darkcoil/releases/tag/v0.9.18.13

will reserve xxx.14 for the openssl fix.

**Comment by schinzelh** [comment]
ok, can do that one too if you like

**Comment by vertoe** [comment]
Ok if you are already at it, go ahead. Cheers.

**Comment by schinzelh** [comment]
No problem, makes things for me easier anyway ^^

**Pull request merged**
